class Character < ApplicationRecord
  belongs_to :user

  has_many :progressions

  enum race: {
    'Dragonborn': 'Dragonborn',
    'Dwarf': 'Dwarf',
    'Elf': 'Elf',
    'Gnome': 'Gnome',
    'Half-elf': 'Half-elf',
    'Half-orc': 'Half-orc',
    'Halfling': 'Halfling',
    'Human': 'Human',
    'Tiefling': 'Tiefling'
  }

  enum background: {
    'Acolyte': 'Acolyte',
    'Anthropologist': 'Anthropologist',
    'Archaeologist': 'Archaeologist',
    'Adopted': 'Adopted',
    'Black Fist Double Agent': 'Black Fist Double Agent',
    'Caravan Specialist': 'Caravan Specialist',
    'Charlatan': 'Charlatan',
    'City Watch': 'City Watch',
    'Clan Crafter': 'Clan Crafter',
    'Cloistered Scholar': 'Cloistered Scholar',
    'Cormanthor Refugee': 'Cormanthor Refugee',
    'Courtier': 'Courtier',
    'Criminal': 'Criminal',
    'Dissenter': 'Dissenter',
    'Dragon Casualty': 'Dragon Casualty',
    'Earthspur Miner': 'Earthspur Miner',
    'Entertainer': 'Entertainer',
    'Faction Agent': 'Faction Agent',
    'Far Traveler': 'Far Traveler',
    'Folk Hero': 'Folk Hero',
    'Gate Urchin': 'Gate Urchin',
    'Gladiator': 'Gladiator',
    'Guild Artisan': 'Guild Artisan',
    'Guild Merchant': 'Guild Merchant',
    'Harborfolk': 'Harborfolk',
    'Haunted One': 'Haunted One',
    'Hermit': 'Hermit',
    'Hillsfar Merchant': 'Hillsfar Merchant',
    'Hillsfar Smuggler': 'Hillsfar Smuggler',
    'House Agent': 'House Agent',
    'Inheritor': 'Inheritor',
    'Initiate': 'Initiate',
    'Inquisitor': 'Inquisitor',
    'Investigator': 'Investigator',
    'Iron Route Bandit': 'Iron Route Bandit',
    'Knight': 'Knight',
    'Knight of the Order': 'Knight of the Order',
    'Mercenary Veteran': 'Mercenary Veteran',
    'Mulmaster Aristocrat': 'Mulmaster Aristocrat',
    'Noble': 'Noble',
    'Outlander': 'Outlander',
    'Phlan Insurgent': 'Phlan Insurgent',
    'Phlan Refugee': 'Phlan Refugee',
    'Pirate': 'Pirate',
    'Sage': 'Sage',
    'Sailor': 'Sailor',
    'Secret Identity': 'Secret Identity',
    'Shade Fanatic': 'Shade Fanatic',
    'Soldier': 'Soldier',
    'Spy': 'Spy',
    'Student Of Magic': 'Student Of Magic',
    'Stojanow Prisoner': 'Stojanow Prisoner',
    'Ticklebelly Nomad': 'Ticklebelly Nomad',
    'Trade Sheriff': 'Trade Sheriff',
    'Urban Bounty Hunter': 'Urban Bounty Hunter',
    'Urchin': 'Urchin',
    'Uthgardt Tribe Member': 'Uthgardt Tribe Member',
    'Vizier': 'Vizier',
    'Waterdhavian Noble': 'Waterdhavian Noble'
  }
end
